//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.SessionState.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.SessionState.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to SQL Server session database..
        /// </summary>
        internal static string Cant_connect_sql_session_database {
            get {
                return ResourceManager.GetString("Cant_connect_sql_session_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;connectionStringName&apos; is missing or empty..
        /// </summary>
        internal static string Connection_name_not_specified {
            get {
                return ResourceManager.GetString("Connection_name_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection name &apos;{0}&apos; was not found in the applications configuration or the connection string is empty..
        /// </summary>
        internal static string Connection_string_not_found {
            get {
                return ResourceManager.GetString("Connection_string_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session state information is invalid and might be corrupted..
        /// </summary>
        internal static string Invalid_session_state {
            get {
                return ResourceManager.GetString("Invalid_session_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login to session state SQL server for user &apos;{0}&apos;..
        /// </summary>
        internal static string Login_failed_sql_session_database {
            get {
                return ResourceManager.GetString("Login_failed_sql_session_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute not recognized &apos;{0}&apos;.
        /// </summary>
        internal static string Provider_unrecognized_attribute {
            get {
                return ResourceManager.GetString("Provider_unrecognized_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is too long..
        /// </summary>
        internal static string Session_id_too_long {
            get {
                return ResourceManager.GetString("Session_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found..
        /// </summary>
        internal static string Session_not_found {
            get {
                return ResourceManager.GetString("Session_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table &apos;{0}&apos; is compatible with a more recent repository type. Use the &apos;{1}&apos; repository type instead..
        /// </summary>
        internal static string SessionTable_current {
            get {
                return ResourceManager.GetString("SessionTable_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table &apos;{0}&apos; was not found in the database. The repositoryType &apos;{1}&apos; cannot create session state tables..
        /// </summary>
        internal static string SessionTable_not_found {
            get {
                return ResourceManager.GetString("SessionTable_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine compatibility type for the table &apos;{0}&apos;..
        /// </summary>
        internal static string SessionTable_unknown {
            get {
                return ResourceManager.GetString("SessionTable_unknown", resourceCulture);
            }
        }
    }
}
