//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.SessionState.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.SessionState.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when reading config secion &apos;{0}&apos;..
        /// </summary>
        internal static string Error_Occured_Reading_Config_Secion {
            get {
                return ResourceManager.GetString("Error_Occured_Reading_Config_Secion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the &apos;{0}&apos; option on provider name &apos;{1}&apos; is invalid..
        /// </summary>
        internal static string Invalid_provider_option {
            get {
                return ResourceManager.GetString("Invalid_provider_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom session state store provider name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Invalid_session_custom_provider {
            get {
                return ResourceManager.GetString("Invalid_session_custom_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom session state store provider &apos;{0}&apos; is not found..
        /// </summary>
        internal static string Missing_session_custom_provider {
            get {
                return ResourceManager.GetString("Missing_session_custom_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionStateAsync module only supports InProc and Custom mode..
        /// </summary>
        internal static string Not_Support_SessionState_Mode {
            get {
                return ResourceManager.GetString("Not_Support_SessionState_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SessionStateStoreData returned by ISessionStateStore has a null value for Items..
        /// </summary>
        internal static string Null_value_for_SessionStateItemCollection {
            get {
                return ResourceManager.GetString("Null_value_for_SessionStateItemCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request queue limit of the session is exceeded..
        /// </summary>
        internal static string Request_Queue_Limit_Per_Session_Exceeded {
            get {
                return ResourceManager.GetString("Request_Queue_Limit_Per_Session_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is too long..
        /// </summary>
        internal static string Session_id_too_long {
            get {
                return ResourceManager.GetString("Session_id_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not inherit from &apos;{1}&apos;..
        /// </summary>
        internal static string Type_doesnt_inherit_from_type {
            get {
                return ResourceManager.GetString("Type_doesnt_inherit_from_type", resourceCulture);
            }
        }
    }
}
